# =========================
# Site Identity
# =========================
title: Sankarasrinivasan Seshathiri   # Main site title for browser tabs, SEO
name: SankaraSrinivasan                # Displayed in header/navigation
description: Postdoctoral Researcher, Computer Vision & AI Specialist  # Optional short bio
avatar: images/circle_crop.jpg         # Profile picture path

# =========================
# Site URL
# =========================
url: "https://vsimkus.github.io/academic-jekyll/"   # Base site URL
baseurl: ""                                         # Set if hosted in a project repo (e.g., /repo-name)

# =========================
# Navigation & Footer
# =========================
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github:
  instagram:
  linkedin:
  pinterest:
  rss:
  twitter:
  stackoverflow:
  youtube:
  googleplus:

# =========================
# Disqus & Analytics
# =========================
disqus:            # Add your Disqus shortname here to enable comments
google_analytics:  # Add your Google Analytics UA code here

# =========================
# Permalinks
# =========================
permalink: /:title/

# =========================
# Jekyll / Markdown
# =========================
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :compressed

# =========================
# Plugins
# =========================
gems:
  - jekyll-sitemap
  # - jekyll-feed

# =========================
# Excluded Files
# =========================
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - command.txt
  - todo.txt
  - _temp/
